spring.application.name=tfphim

# PostgreSQL online database configuration
spring.datasource.url=jdbc:postgresql://shinkansen.proxy.rlwy.net:12655/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=FrNusyQPLqHyaiaKqiijSZjQkoCeuxYq
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true





# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TFFilm;encrypt=false;sendStringParametersAsUnicode=true;
# spring.datasource.username=philt
# spring.datasource.password=0000
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
# spring.jpa.show-sql=true




# src/main/resources/application.properties
# server.port=8080
server.port=${PORT:8080}
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
