spring.application.name=tfphim

# src/main/resources/application.properties
# server.port=8080
server.port=${PORT:8080}

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

kkphim.api.base-url=${KKPHIM_API_BASE_URL:https://phimapi.com}
ophim.api.base-url=${OPHIM_API_BASE_URL:https://ophim1.com}
